 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("누가바", "하드", 1000, "해태", 20, "얇은 누가 초콜릿 안에 바닐라 크림이 들어있어요")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("월드콘", "콘", 3500, "롯데제과", 15, "축구는 월드컵!야구는 월드 시리즈!아이스크림은~~~!? 월드콘!!!!")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("빵또아", "기타", 2500, "빙그레", 10, "부드럽고 얇은 두 개의 카스테라 빵 사이에 쿠키 앤 크림 아이스크림을 블록 모양으로 넣은 제품")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("보석바", "하드", 1000, "롯데푸드", 5, "전체적으로 우유빛을 띄며 요구르트와 밀키스 사이 어딘가의 맛을 내는 아이스크림")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("바밤바", "하드", 1000, "해태", 35, "밤맛을 강조하고 있으며, 아이스크림에도 중간중간에 밤 쪼가리가 섞여있어요")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("부라보콘", "콘", 3000, "해태", 20, "1970년 해태제과에서 출시한 대한민국 최초의 아이스콘")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("폴라포", "기타", 1500, "해태", 40, "1984년 해태에서 출시된 위로 밀어서 먹는 펜슬형 아이스바")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("빠삐코", "쭈쭈바", 2000, "롯데푸드", 25, "보편적인 초코 아이스 슬러시맛. 슬러시랑 비교했을때 맛이 진하고 점성이 높으며 알갱이가 작아 금방 녹이요")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("수박바", "하드", 1000, "롯데제과", 10, "수박 모양의 아이스크림")
 insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("뽕따", "쭈쭈바", 1500, "빙그레", 30, "소다맛을 녹이면 천연사이다와 유사한 맛이 나요")
